//! The built-in manual, served by `intact guide [TOPIC]`.
//!
//! The executable is meant to be self-documenting: an agent handed nothing but
//! the binary must be able to discover the entire API starting from `--help`.
//! Everything the README says lives here too, so the two never drift apart in
//! the only direction that matters — the binary is the source of truth.
//!
//! A section body is structured (see [`block`]), not pre-formatted, so the
//! terminal manual and MANUAL.md are two renderings of one source.

mod block;
mod instructions;
mod sections;

pub use block::Block;
pub use instructions::{InstructionsSpec, instructions};
pub use sections::SECTIONS;

pub struct Section {
    pub key: &'static str,
    pub title: &'static str,
    pub summary: &'static str,
    pub body: &'static [Block],
}

pub fn find(topic: &str) -> Option<&'static Section> {
    let needle = topic.trim().to_ascii_lowercase();
    SECTIONS.iter().find(|s| s.key == needle)
}

pub fn topic_list() -> String {
    let width = SECTIONS.iter().map(|s| s.key.len()).max().unwrap_or(0);
    let mut out = String::from("Manual topics (`intact guide TOPIC`):\n\n");
    for section in SECTIONS {
        out.push_str(&format!("  {:<width$}  {}\n", section.key, section.summary));
    }
    out.push_str("\n`intact guide` with no topic prints all of them.\n");
    out
}

// ------------------------------------------------------------------- plain

/// Each heading carries the topic key, so a reader of the full manual knows how
/// to ask for that one section again.
fn heading(section: &Section) -> String {
    let line = format!("{}  (intact guide {})", section.title, section.key);
    format!("{line}\n{}\n", "-".repeat(line.chars().count()))
}

pub fn render_all() -> String {
    let mut out = String::from("intact manual\n===============\n");
    for section in SECTIONS {
        out.push_str(&format!("\n\n{}\n", heading(section)));
        out.push_str(&block::plain(section.body));
    }
    out.push_str("\n\nSee also: `intact COMMAND --help` for a single command, and\n");
    out.push_str("`intact instructions` for a section to paste into a project's CLAUDE.md.\n");
    out
}

pub fn render_one(section: &Section) -> String {
    format!("{}\n{}", heading(section), block::plain(section.body))
}

// ---------------------------------------------------------------- markdown

/// The whole manual as Markdown — the file MANUAL.md is, generated rather than
/// written so it cannot fall behind the binary.
pub fn render_all_markdown() -> String {
    let mut out = String::from(MARKDOWN_PREAMBLE);
    for section in SECTIONS {
        // No explicit anchor: `{#id}` is not GitHub-flavoured Markdown and
        // would render as literal text. GitHub derives the anchor from the
        // heading, so the topic key goes in the line under it instead, where
        // it also tells a reader how to ask for this one section.
        out.push_str(&format!("\n## {}\n\n", block::sentence_case(section.title)));
        out.push_str(&format!("*`intact guide {}`*\n\n", section.key));
        out.push_str(&block::markdown(section.body, 3));
    }
    out.push_str(
        "\n---\n\nSee also `intact COMMAND --help` for a single command, and\n\
         `intact instructions` for a section to paste into a project's CLAUDE.md.\n",
    );
    out
}

pub fn render_one_markdown(section: &Section) -> String {
    // The topic key rides along here as it does in the plain rendering, so a
    // section saved on its own still says how to ask for it again.
    let mut out = format!("# {}\n\n", block::sentence_case(section.title));
    out.push_str(&format!("*`intact guide {}`*\n\n", section.key));
    out.push_str(&block::markdown(section.body, 2));
    out
}

const MARKDOWN_PREAMBLE: &str = "\
# intact — full manual

This file is generated by `intact guide --markdown` from the manual built into
the binary, so it is never stale. Do not edit it by hand: run
`scripts/gen-manual.sh` after changing anything under `src/manual/`, then commit
the result.

For one topic at a time: `intact guide TOPIC` (list them with
`intact guide --list`, or see the table in [README.md](README.md#commands)).
";
